In [1]:
import numpy as np

In [3]:
l = [11,22,33]
l

[11, 22, 33]

In [4]:
type(l)

list

In [5]:
type(l[0])

int

In [6]:
#numpy

In [7]:
x = np.array([11,22,33])
x

array([11, 22, 33])

In [9]:
type(x[0])

numpy.int64

In [10]:
import pandas as pd
df = pd.read_csv("sample_data_01.csv")
df.head()

都道府県      総人口   総人口(男)   総人口(女)     日本人口  外国人人口       総面積     可住地面積  県内総生産額  \
0  北海道  5250000  2472000  2778000  5211000  21676  83456.87  22699.23  194301   
1  青森県  1246000   585000   661000  1240000   3447   9644.54   3253.19   44432   
2  岩手県  1227000   592000   635000  1219000   5017  15278.89   3751.37   46512   
3  宮城県  2306000  1127000  1179000  2283000  13989   7285.76   3185.91   94639   
4  秋田県   966000   454000   512000   963000   2914  11636.25   3233.34   35630   

     県民取得  ...  コンビニ数   飲食店数  公衆浴場数  一般病院数   薬局数  世帯主の配偶者の収入    消費支出    住居費  \
0  142696  ...   2194  26585    256    484  2333       73207  334015  27305   
1   31833  ...    404   6744    287     77   619       83166  278356  18537   
2   34779  ...    398   5668     18     76   605      113215  293157  24850   
3   68388  ...    777   9560      7    112  1165       51130  285393  24121   
4   26876  ...    309   4704     13     52   521      102944  300312  14661   

   光熱・水道費   教育費  
0   27309  9394  
1   27837  3841  
2   27129  6573  
3   22717  6955  
4   25743  4394  

[5 rows x 33 columns]

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df["県民取得"].head()

0    142696
1     31833
2     34779
3     68388
4     26876
Name: 県民取得, dtype: int64

In [13]:
type(df["県民取得"])

pandas.core.series.Series

In [16]:
df["県民取得"][0]

142696

In [15]:
type(df["県民取得"][0])

numpy.int64

In [17]:
df["県民取得"].values

array([142696,  31833,  34779,  68388,  26876,  32206,  55926,  95623,
        66792,  65157, 224157, 199398, 744732, 295540,  65108,  35052,
        33992,  25421,  24474,  61024,  57207, 124537, 277282,  55995,
        46466,  78452, 280818, 163220,  35036,  26431,  14041,  17485,
        54152,  89593,  45057,  22973,  29200,  37391,  18915, 147459,
        21665,  34812,  46134,  31222,  27082,  40512,  33893])

In [18]:
type(df["県民取得"].values)

numpy.ndarray

In [19]:
x = np.array([11,22,33,44,55])

In [21]:
x.max()

55

In [22]:
x.min()

11

In [23]:
x.sum()

165

In [24]:
x.mean()

33.0

In [25]:
df["総人口"].values.mean()

2684404.255319149

In [26]:
df["県民取得"].values.mean()

89068.17021276595

In [28]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
x.shape

(2, 3)

In [30]:
df.values.shape

(47, 33)

In [43]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x.reshape(5,2)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x = np.arange(0,2,0.5)
x

array([0. , 0.5, 1. , 1.5])

In [41]:
x.reshape(2,2)

array([[0. , 0.5],
       [1. , 1.5]])

In [45]:
x = np.arange(1,11,2)
y = np.arange(1,6)

In [46]:
x

array([1, 3, 5, 7, 9])

In [47]:
y

array([1, 2, 3, 4, 5])

In [48]:
np.append(x,y)

array([1, 3, 5, 7, 9, 1, 2, 3, 4, 5])

In [49]:
np.vstack([x,y])

array([[1, 3, 5, 7, 9],
       [1, 2, 3, 4, 5]])

In [50]:
np.hstack([x,y])

array([1, 3, 5, 7, 9, 1, 2, 3, 4, 5])

In [51]:
x + y

array([ 2,  5,  8, 11, 14])

In [52]:
x - y

array([0, 1, 2, 3, 4])

In [53]:
x < y

array([False, False, False, False, False])

In [54]:
x > y

array([False,  True,  True,  True,  True])

In [61]:
y = np.append(y,6)

In [62]:
y.shape

(6,)

In [63]:
x.shape

(5,)